routes/web.php
<?php
use Illuminate\Support\Facades\Input as Input;
use App\Customer;
use App\Article;
use App\Config;
use App\Sale;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('customers','CustomerController');
Route::resource('articles','ArticleController');
Route::resource('configs','ConfigController');
Route::resource('sales','SaleController');


Route::get('/getSales', 'SaleController@getSales');

Route::get('/customersget/',function(){
 $query = Input::get('query');
 $customers = Customer::where('name','like','%'.$query.'%')->orWhere('father_lastname','like','%'.$query.'%')->orWhere('mother_lastname','like','%'.$query.'%')->get();
 return response()->json($customers);
});

Route::get('/articlesget',function(){
 $queryart = Input::get('queryart');
 $articles = Article::where('description','like','%'.$queryart.'%')->orWhere('model','like','%'.$queryart.'%')->get();
 return response()->json($articles);
});

Route::get('/getprice',function(){
 $article_id = Input::get('id');
 $config = Config::orderBy('created_at','desc')->first();
 $article = Article::find($article_id);
 //Precio = Precio Articulo X (1 + (Tasa Financiamiento X Plazo Máximo) /100)
 $price = $article->price * (1+($config->financing_rate * $config->deadline) / 100);
 return response()->json(round($price,2));
 // $articles = Article::where('description','like','%'.$queryart.'%')->orWhere('model','like','%'.$queryart.'%')->get();
 // return response()->json($articles);
});

Route::get('/getTotales',function(){
 $sumAmount = Input::get('sumAmount');
 $config = Config::orderBy('created_at','DESC')->first();
 $totales["amount"] = round($sumAmount,2);
 $totales["hooking"] =  round(($config->hooking_percentage/100) * $totales["amount"],2);
 $totales["hooking_bonus"] = round($totales["hooking"] * (($config->financing_rate * $config->deadline) /100),2);
 $totales["total"] =   round($totales["amount"] - $totales["hooking"] - $totales["hooking_bonus"],2);
 return response()->json($totales);
});

Route::get('/getPlazos',function(){
 $sumAmount = Input::get('sumAmount');
 $config = Config::orderBy('created_at','DESC')->first();

 $plazos[3]["precio_contado"] = $sumAmount / (1 + (($config->financing_rate * $config->deadline) / 100));
 $plazos[3]["plazo"] = 3;
 $plazos[3]["total"] = round($plazos[3]["precio_contado"] * (1 + ($config->financing_rate * 3) / 100),2);
 $plazos[3]["abono"] = round($plazos[3]["total"] / 3,2);
 $plazos[3]["ahorro"] = round($sumAmount - $plazos[3]["total"],2);

 $plazos[6]["plazo"] = 6;
 $plazos[6]["total"] =  round($plazos[3]["precio_contado"] * (1 + ($config->financing_rate * 6) / 100),2);
 $plazos[6]["abono"] = round($plazos[6]["total"] / 6,2);
 $plazos[6]["ahorro"] = round($sumAmount - $plazos[6]["total"],2);

 $plazos[9]["plazo"] = 9;
 $plazos[9]["total"] = round($plazos[3]["precio_contado"] * (1 + ($config->financing_rate * 9) / 100),2);
 $plazos[9]["abono"] = round($plazos[9]["total"] / 9,2);
 $plazos[9]["ahorro"] = round($sumAmount - $plazos[9]["total"],2);

 $plazos[12]["plazo"] = 12;
 $plazos[12]["total"] = round($plazos[3]["precio_contado"] * (1 + ($config->financing_rate * 12) / 100),2);
 $plazos[12]["abono"] = round($plazos[12]["total"] / 12,2);
 $plazos[12]["ahorro"] = round($sumAmount - $plazos[12]["total"],2);

 return response()->json($plazos);
});

Route::post('/saveSale',function(){
	//QUITAR EXISTENCIAS DE LOS ARTÍCULOS
	$articles = Input::get('articles');
	foreach ($articles as $art) {

		$article = Article::find($art["id"]);
		$article->existence = $article->existence - $art["quantity"];
		$article->save();
	}

	$config = Config::orderBy('created_at','DESC')->first();
	$sale = new Sale;
	$sale->customer_id = Input::get('customer_id');
	$sale->hooking = Input::get('hooking');
	$sale->hooking_bonus = Input::get('hooking_bonus');
	$sale->total_owed = Input::get('total_owed');
	$sale->monthly_payment_number = Input::get('monthly_payment_number');
	$sale->cash_price = Input::get('total_owed') / (1 + (($config->financing_rate * $config->deadline) / 100));
	$sale->payment_ammount = round( Input::get('total_owed')/ $sale->monthly_payment_number ,2);
 	$sale->monthly_payment_number = Input::get('monthly_payment_number');
 	$sale->save();
 	return response()->json($sale);
});

app/Config.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Config extends Model
{
    protected $fillable = [
        'financing_rate', 'hooking_percentage', 'deadline'
    ];
}

app/Http/Controllers/ConfigController.php
<?php

namespace App\Http\Controllers;

use App\Config;
use Illuminate\Http\Request;

class ConfigController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $configs = Config::all();
        $config = $configs->last();

        if(!empty($config)){

            return view('configs.edit',compact('config'));
        }

        return view('configs.create');
    }

    public function create(){
        return view('configs.create');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $messages = [
            'financing_rate.numeric' => 'Tasa de Financiamiento debe ser un número.',
            'hooking_percentage.numeric' => '% de Enganche debe ser un número.',
            'deadline.numeric' => 'Plazo Máximo debe ser un número.',
        ];

        $request->validate([
            'financing_rate' => 'numeric',
            'hooking_percentage' => 'numeric',
            'deadline' => 'numeric',
        ], $messages);
  
        Config::create($request->all());
   
        return redirect()->route('configs.index')
                        ->with('success','“Bien Hecho. La configuración ha sido registrada”.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Config  $config
     * @return \Illuminate\Http\Response
     */
    public function show(Config $config)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Config  $config
     * @return \Illuminate\Http\Response
     */
    public function edit(Config $config)
    {
        return view('configs.edit',compact($config));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Config  $config
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Config $config)
    {
         $messages = [
            'financing_rate.numeric' => 'Tasa de Financiamiento debe ser un número.',
            'hooking_percentage.numeric' => '% de Enganche debe ser un número.',
            'deadline.numeric' => 'Plazo Máximo debe ser un número.',
        ];

        $request->validate([
            'financing_rate' => 'numeric',
            'hooking_percentage' => 'numeric',
            'deadline' => 'numeric',
        ], $messages);
  
        $config->update($request->all());
  
        return redirect()->route('configs.index')
                        ->with('success','Bien Hecho. La configuración ha sido registrada.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Config  $config
     * @return \Illuminate\Http\Response
     */
    public function destroy(Config $config)
    {
        //
    }
}

resources/views/configs/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    
    <div class="card" style="color:green;">

      <div class="card-header bg-primary">
        <span class="text-white">Configuración General</span>
      </div>
        <div class="card-body">

            <form  action="{{ route('configs.store') }}" method="POST">
                @csrf <!-- {{ csrf_field() }} -->
                
              <div class="form-group row text-right">
                <label for="financing_rate" class="col-sm-2 col-form-label">Tasa Financiamiento:</label>
                <div class="col-sm-4">
                  <input type="text" name="financing_rate" class="form-control" id="financing_rate" value="{{ old('financing_rate') }}">
                </div>
              </div>

              <div class="form-group row text-right">
                <label for="hooking_percentage" class="col-sm-2 col-form-label">% Enganche:</label>
                <div class="col-sm-4">
                  <input type="text" name="hooking_percentage" class="form-control" id="hooking_percentage" value="{{ old('hooking_percentage') }}">
                </div>
              </div>

              <div class="form-group row text-right">
                <label for="deadline" class="col-sm-2 col-form-label">Plazo Máximo:</label>
                <div class="col-sm-4">
                  <input type="text" name="deadline" class="form-control" id="deadline" value="{{ old('deadline') }}">
                </div>
              </div>

        

              <div class="form-group row text-right">
                <div class="col-sm-10">
                  <a class="btn btn-success" href="{{ "/home" }}">Cancelar</a>
                  <button type="submit" class="btn btn-success">Guardar</button>
                </div>
              </div>

            </form>
    
        </div>

    </div>  
</div>

@endsection

resources/views/configs/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    
    <div class="card" style="color:green;">

      <div class="card-header bg-primary">
        <span class="text-white">Configuración General</span>
      </div>
        <div class="card-body">

            <form  action="{{ route('configs.update', $config->id) }}" method="POST">
                @csrf <!-- {{ csrf_field() }} -->
                @method('PUT')
              <div class="form-group row text-right">
                <label for="financing_rate" class="col-sm-2 col-form-label">Tasa Financiamiento:</label>
                <div class="col-sm-4">
                  <input type="text" name="financing_rate" class="form-control" id="financing_rate" value="{{ $config->financing_rate }}">
                </div>
              </div>

              <div class="form-group row text-right">
                <label for="hooking_percentage" class="col-sm-2 col-form-label">% Enganche:</label>
                <div class="col-sm-4">
                  <input type="text" name="hooking_percentage" class="form-control" id="hooking_percentage" value="{{ $config->hooking_percentage }}">
                </div>
              </div>

              <div class="form-group row text-right">
                <label for="deadline" class="col-sm-2 col-form-label">Plazo Máximo:</label>
                <div class="col-sm-4">
                  <input type="text" name="deadline" class="form-control" id="deadline" value="{{ $config->deadline }}">
                </div>
              </div>

        

              <div class="form-group row text-right">
                <div class="col-sm-10">
                  <a class="btn btn-success" href="{{ "/home" }}">Cancelar</a>
                  <button type="submit" class="btn btn-success">Guardar</button>
                </div>
              </div>

            </form>
    
        </div>

    </div>  
</div>

@endsection