routes/web.php
<?php
use Illuminate\Support\Facades\Input as Input;
use App\Customer;
use App\Article;
use App\Config;
use App\Sale;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('customers','CustomerController');
Route::resource('articles','ArticleController');
Route::resource('configs','ConfigController');
Route::resource('sales','SaleController');


Route::get('/getSales', 'SaleController@getSales');

Route::get('/customersget/',function(){
 $query = Input::get('query');
 $customers = Customer::where('name','like','%'.$query.'%')->orWhere('father_lastname','like','%'.$query.'%')->orWhere('mother_lastname','like','%'.$query.'%')->get();
 return response()->json($customers);
});

Route::get('/articlesget',function(){
 $queryart = Input::get('queryart');
 $articles = Article::where('description','like','%'.$queryart.'%')->orWhere('model','like','%'.$queryart.'%')->get();
 return response()->json($articles);
});

Route::get('/getprice',function(){
 $article_id = Input::get('id');
 $config = Config::orderBy('created_at','desc')->first();
 $article = Article::find($article_id);
 //Precio = Precio Articulo X (1 + (Tasa Financiamiento X Plazo Máximo) /100)
 $price = $article->price * (1+($config->financing_rate * $config->deadline) / 100);
 return response()->json(round($price,2));
 // $articles = Article::where('description','like','%'.$queryart.'%')->orWhere('model','like','%'.$queryart.'%')->get();
 // return response()->json($articles);
});

Route::get('/getTotales',function(){
 $sumAmount = Input::get('sumAmount');
 $config = Config::orderBy('created_at','DESC')->first();
 $totales["amount"] = round($sumAmount,2);
 $totales["hooking"] =  round(($config->hooking_percentage/100) * $totales["amount"],2);
 $totales["hooking_bonus"] = round($totales["hooking"] * (($config->financing_rate * $config->deadline) /100),2);
 $totales["total"] =   round($totales["amount"] - $totales["hooking"] - $totales["hooking_bonus"],2);
 return response()->json($totales);
});

Route::get('/getPlazos',function(){
 $sumAmount = Input::get('sumAmount');
 $config = Config::orderBy('created_at','DESC')->first();

 $plazos[3]["precio_contado"] = $sumAmount / (1 + (($config->financing_rate * $config->deadline) / 100));
 $plazos[3]["plazo"] = 3;
 $plazos[3]["total"] = round($plazos[3]["precio_contado"] * (1 + ($config->financing_rate * 3) / 100),2);
 $plazos[3]["abono"] = round($plazos[3]["total"] / 3,2);
 $plazos[3]["ahorro"] = round($sumAmount - $plazos[3]["total"],2);

 $plazos[6]["plazo"] = 6;
 $plazos[6]["total"] =  round($plazos[3]["precio_contado"] * (1 + ($config->financing_rate * 6) / 100),2);
 $plazos[6]["abono"] = round($plazos[6]["total"] / 6,2);
 $plazos[6]["ahorro"] = round($sumAmount - $plazos[6]["total"],2);

 $plazos[9]["plazo"] = 9;
 $plazos[9]["total"] = round($plazos[3]["precio_contado"] * (1 + ($config->financing_rate * 9) / 100),2);
 $plazos[9]["abono"] = round($plazos[9]["total"] / 9,2);
 $plazos[9]["ahorro"] = round($sumAmount - $plazos[9]["total"],2);

 $plazos[12]["plazo"] = 12;
 $plazos[12]["total"] = round($plazos[3]["precio_contado"] * (1 + ($config->financing_rate * 12) / 100),2);
 $plazos[12]["abono"] = round($plazos[12]["total"] / 12,2);
 $plazos[12]["ahorro"] = round($sumAmount - $plazos[12]["total"],2);

 return response()->json($plazos);
});

Route::post('/saveSale',function(){
	//QUITAR EXISTENCIAS DE LOS ARTÍCULOS
	$articles = Input::get('articles');
	foreach ($articles as $art) {

		$article = Article::find($art["id"]);
		$article->existence = $article->existence - $art["quantity"];
		$article->save();
	}

	$config = Config::orderBy('created_at','DESC')->first();
	$sale = new Sale;
	$sale->customer_id = Input::get('customer_id');
	$sale->hooking = Input::get('hooking');
	$sale->hooking_bonus = Input::get('hooking_bonus');
	$sale->total_owed = Input::get('total_owed');
	$sale->monthly_payment_number = Input::get('monthly_payment_number');
	$sale->cash_price = Input::get('total_owed') / (1 + (($config->financing_rate * $config->deadline) / 100));
	$sale->payment_ammount = round( Input::get('total_owed')/ $sale->monthly_payment_number ,2);
 	$sale->monthly_payment_number = Input::get('monthly_payment_number');
 	$sale->save();
 	return response()->json($sale);
});

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Sale;

class Customer extends Model
{
    protected $fillable = [
        'name', 'father_lastname', 'mother_lastname', 'rfc'
    ];

    public function sales(){
    	return $this->hasMany(Sale::class);
    }

    public function getFullNameAttribute() {
        return ucfirst($this->name) . ' ' . ucfirst($this->father_lastname) . ' ' . ucfirst($this->mother_lastname);
    }


}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Customer;
use Illuminate\Http\Request;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customers = Customer::latest()->paginate(5);
  
        return view('customers.index',compact('customers'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $customers = Customer::all();
        $customer = $customers->last();

        return view('customers.create',compact('customer'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $messages = [
            'name.required' => 'Nombre es requerido.',
            'father_lastname.required' => 'Apellido Paterno es requerido.',
            'mother_lastname.required' => 'Apellido Materno es requerido.',
            'rfc.required' => 'RFC es requerido.',
            'rfc.unique' => 'Ya existe un cliente con ese RFC',
        ];

        $request->validate([
            'name' => 'required',
            'father_lastname' => 'required',
            'mother_lastname' => 'required',
            'rfc' => ['unique:customers,rfc','required'],
        ], $messages);
  
        Customer::create($request->all());
   
        return redirect()->route('customers.index')
                        ->with('success','“Bien Hecho. El cliente ha sido registrado correctamente”.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function show(Customer $customer)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function edit(Customer $customer)
    {
        return view('customers.edit',compact('customer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Customer $customer)
    {
        $messages = [
            'name.required' => 'Nombre es requerido.',
            'father_lastname.required' => 'Apellido Paterno es requerido.',
            'mother_lastname.required' => 'Apellido Materno es requerido.',
            'rfc.required' => 'RFC es requerido.',
            'rfc.unique' => 'Ya existe un cliente con ese RFC',
        ];

        $request->validate([
            'name' => 'required',
            'father_lastname' => 'required',
            'mother_lastname' => 'required',
            'rfc' => ['unique:customers,rfc,'.$customer->id,'required'],
        ], $messages);
  
        $customer->update($request->all());
  
        return redirect()->route('customers.index')
                        ->with('success','Se actualizó el Cliente con éxito.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Customer $customer)
    {
        //
    }
}

resources/views/customers/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    
    <div class="card" style="color:green;">

      <div class="card-header bg-primary">
        <span class="text-white">Registro de Clientes</span>
      </div>
    
        <div class="card-body">
            <p class="card-title text-right" style="margin-right: 50px;">Clave: 

              @if(!empty($article))
                 {{ $article->id + 1 }}
              @else
                1
              @endif
            </p> 
            <form  action="{{ route('customers.store') }}" method="POST">
                @csrf <!-- {{ csrf_field() }} -->
                
              <div class="form-group row text-right">
                <label for="name" class="col-sm-2 col-form-label">Nombre:</label>
                <div class="col-sm-4">
                  <input type="text" name="name" class="form-control" id="name" value="{{ old('name') }}">
                </div>
              </div>

              <div class="form-group row text-right">
                <label for="father_lastname" class="col-sm-2 col-form-label">Apellido Paterno:</label>
                <div class="col-sm-4">
                  <input type="text" name="father_lastname" class="form-control" id="father_lastname" value="{{ old('father_lastname') }}">
                </div>
              </div>

              <div class="form-group row text-right">
                <label for="mother_lastname" class="col-sm-2 col-form-label">Apellido Materno:</label>
                <div class="col-sm-4">
                  <input type="text" name="mother_lastname" class="form-control" id="mother_lastname" value="{{ old('mother_lastname') }}">
                </div>
              </div>

              <div class="form-group row text-right">
                <label for="rfc" class="col-sm-2 col-form-label">RFC:</label>
                <div class="col-sm-4">
                  <input type="text" name="rfc" class="form-control" id="rfc" value="{{ old('rfc') }}">
                </div>
              </div>

              <div class="form-group row text-right">
                <div class="col-sm-10">
                  <a class="btn btn-success" href="{{ route('customers.index') }}">Cancelar</a>
                  <button type="submit" class="btn btn-success">Guardar</button>
                </div>
              </div>

            </form>
    
        </div>

    </div>


    {{-- <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('customers.index') }}"> Back</a>
            </div>
        </div>
    </div> --}}
       
    {{-- @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif --}}
       
    {{-- <form action="{{ route('customers.store') }}" method="POST">
        @csrf
      
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Detail:</strong>
                    <textarea class="form-control" style="height:150px" name="detail" placeholder="Detail"></textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
       
    </form> --}}   
</div>

@endsection

resources/views/customers/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    
    <div class="card" style="color:green;">

      <div class="card-header bg-primary">
        <span class="text-white">Editar Cliente</span>
      </div>
    
        <div class="card-body">
            <p class="card-title text-right" style="margin-right: 50px;">Clave: {{$customer->id}} </p>


            <form  action="{{ route('customers.update',$customer->id) }}" method="POST">
                @csrf <!-- {{ csrf_field() }} -->
                @method('PUT')
              <div class="form-group row text-right">
                <label for="name" class="col-sm-2 col-form-label">Nombre:</label>
                <div class="col-sm-4">
                  <input type="text" name="name" class="form-control" id="name" value="{{ $customer->name }}">
                </div>
              </div>

              <div class="form-group row text-right">
                <label for="father_lastname" class="col-sm-2 col-form-label">Apellido Paterno:</label>
                <div class="col-sm-4">
                  <input type="text" name="father_lastname" class="form-control" id="father_lastname" value="{{ $customer->father_lastname }}">
                </div>
              </div>

              <div class="form-group row text-right">
                <label for="mother_lastname" class="col-sm-2 col-form-label">Apellido Materno:</label>
                <div class="col-sm-4">
                  <input type="text" name="mother_lastname" class="form-control" id="mother_lastname" value="{{ $customer->mother_lastname }}">
                </div>
              </div>

              <div class="form-group row text-right">
                <label for="rfc" class="col-sm-2 col-form-label">RFC:</label>
                <div class="col-sm-4">
                  <input type="text" name="rfc" class="form-control" id="rfc" value="{{ $customer->rfc }}">
                </div>
              </div>

              <div class="form-group row text-right">
                <div class="col-sm-10">
                  <a class="btn btn-success" href="{{ route('customers.index') }}">Cancelar</a>
                  <button type="submit" class="btn btn-success">Guardar</button>
                </div>
              </div>

            </form>
    
        </div>

    </div>
</div>

@endsection

resources/views/customers/index.blade.php
@extends('layouts.app')
 
@section('content')
    
<div class="container">
    

    

   <div class="row">

       <div class="col-8">
           <h4 class="text-primary" style="position: absolute;
   bottom:0px; top:12px;">Clientes Registrados</h4>
       </div>
       <div class="col text-right">

           <a href="{{ route('customers.create') }}" class="btn btn-primary btn-lg" style="color:white">
            <i style="font-size:40px; color:#38c172; vertical-align:middle; " class="material-icons">add_circle</i> 
              Nuevo Cliente</a>
       </div>
       

   </div>
   <hr>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Clave Cliente</th>
          <th scope="col">Nombre</th>
          <th width="280px">Acción</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($customers as $customer)
            <tr>
              <td>{{$customer->id}}</td>
              <td>{{$customer->name}} {{$customer->father_lastname}} {{$customer->mother_lastname}}</td>
              <td>
     
                <a title="editar cliente" href="{{ route('customers.edit',$customer->id) }}"><i class="material-icons">edit</i>
                </a>

              </td>
            </tr>
           
        @endforeach
      </tbody>
    </table>
  
    {!! $customers->links() !!}
</div>
      
@endsection