routes/web.php
<?php
use Illuminate\Support\Facades\Input as Input;
use App\Customer;
use App\Article;
use App\Config;
use App\Sale;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('customers','CustomerController');
Route::resource('articles','ArticleController');
Route::resource('configs','ConfigController');
Route::resource('sales','SaleController');


Route::get('/getSales', 'SaleController@getSales');

Route::get('/customersget/',function(){
 $query = Input::get('query');
 $customers = Customer::where('name','like','%'.$query.'%')->orWhere('father_lastname','like','%'.$query.'%')->orWhere('mother_lastname','like','%'.$query.'%')->get();
 return response()->json($customers);
});

Route::get('/articlesget',function(){
 $queryart = Input::get('queryart');
 $articles = Article::where('description','like','%'.$queryart.'%')->orWhere('model','like','%'.$queryart.'%')->get();
 return response()->json($articles);
});

Route::get('/getprice',function(){
 $article_id = Input::get('id');
 $config = Config::orderBy('created_at','desc')->first();
 $article = Article::find($article_id);
 //Precio = Precio Articulo X (1 + (Tasa Financiamiento X Plazo Máximo) /100)
 $price = $article->price * (1+($config->financing_rate * $config->deadline) / 100);
 return response()->json(round($price,2));
 // $articles = Article::where('description','like','%'.$queryart.'%')->orWhere('model','like','%'.$queryart.'%')->get();
 // return response()->json($articles);
});

Route::get('/getTotales',function(){
 $sumAmount = Input::get('sumAmount');
 $config = Config::orderBy('created_at','DESC')->first();
 $totales["amount"] = round($sumAmount,2);
 $totales["hooking"] =  round(($config->hooking_percentage/100) * $totales["amount"],2);
 $totales["hooking_bonus"] = round($totales["hooking"] * (($config->financing_rate * $config->deadline) /100),2);
 $totales["total"] =   round($totales["amount"] - $totales["hooking"] - $totales["hooking_bonus"],2);
 return response()->json($totales);
});

Route::get('/getPlazos',function(){
 $sumAmount = Input::get('sumAmount');
 $config = Config::orderBy('created_at','DESC')->first();

 $plazos[3]["precio_contado"] = $sumAmount / (1 + (($config->financing_rate * $config->deadline) / 100));
 $plazos[3]["plazo"] = 3;
 $plazos[3]["total"] = round($plazos[3]["precio_contado"] * (1 + ($config->financing_rate * 3) / 100),2);
 $plazos[3]["abono"] = round($plazos[3]["total"] / 3,2);
 $plazos[3]["ahorro"] = round($sumAmount - $plazos[3]["total"],2);

 $plazos[6]["plazo"] = 6;
 $plazos[6]["total"] =  round($plazos[3]["precio_contado"] * (1 + ($config->financing_rate * 6) / 100),2);
 $plazos[6]["abono"] = round($plazos[6]["total"] / 6,2);
 $plazos[6]["ahorro"] = round($sumAmount - $plazos[6]["total"],2);

 $plazos[9]["plazo"] = 9;
 $plazos[9]["total"] = round($plazos[3]["precio_contado"] * (1 + ($config->financing_rate * 9) / 100),2);
 $plazos[9]["abono"] = round($plazos[9]["total"] / 9,2);
 $plazos[9]["ahorro"] = round($sumAmount - $plazos[9]["total"],2);

 $plazos[12]["plazo"] = 12;
 $plazos[12]["total"] = round($plazos[3]["precio_contado"] * (1 + ($config->financing_rate * 12) / 100),2);
 $plazos[12]["abono"] = round($plazos[12]["total"] / 12,2);
 $plazos[12]["ahorro"] = round($sumAmount - $plazos[12]["total"],2);

 return response()->json($plazos);
});

Route::post('/saveSale',function(){
	//QUITAR EXISTENCIAS DE LOS ARTÍCULOS
	$articles = Input::get('articles');
	foreach ($articles as $art) {

		$article = Article::find($art["id"]);
		$article->existence = $article->existence - $art["quantity"];
		$article->save();
	}

	$config = Config::orderBy('created_at','DESC')->first();
	$sale = new Sale;
	$sale->customer_id = Input::get('customer_id');
	$sale->hooking = Input::get('hooking');
	$sale->hooking_bonus = Input::get('hooking_bonus');
	$sale->total_owed = Input::get('total_owed');
	$sale->monthly_payment_number = Input::get('monthly_payment_number');
	$sale->cash_price = Input::get('total_owed') / (1 + (($config->financing_rate * $config->deadline) / 100));
	$sale->payment_ammount = round( Input::get('total_owed')/ $sale->monthly_payment_number ,2);
 	$sale->monthly_payment_number = Input::get('monthly_payment_number');
 	$sale->save();
 	return response()->json($sale);
});

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Sale;

class Customer extends Model
{
    protected $fillable = [
        'name', 'father_lastname', 'mother_lastname', 'rfc'
    ];

    public function sales(){
    	return $this->hasMany(Sale::class);
    }

    public function getFullNameAttribute() {
        return ucfirst($this->name) . ' ' . ucfirst($this->father_lastname) . ' ' . ucfirst($this->mother_lastname);
    }


}

app/Sale.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Customer;

class Sale extends Model
{
    protected $fillable = [
        'customer_id'
    ];

    public function customer(){
    	return $this->belongsTo(Customer::class);
    }
}

app/Http/Controllers/SaleController.php
<?php

namespace App\Http\Controllers;

use App\Sale;
use Illuminate\Http\Request;

class SaleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sales = Sale::latest()->paginate(5);
  
        return view('sales.index',compact('sales'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }


    public function getSales(){
        $sales = Sale::all();
        return $sales;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $sales = Sale::all();
        $sale = $sales->last();

        return view('sales.create',compact('sale'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'customer_id' => 'required'
        ]);

        Sale::create($request->all());

        return;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Sale  $sale
     * @return \Illuminate\Http\Response
     */
    public function show(Sale $sale)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Sale  $sale
     * @return \Illuminate\Http\Response
     */
    public function edit(Sale $sale)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Sale  $sale
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'customer_id' => 'required',
        ]);

        Sale::find($id)->update($request->all());

        return;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Sale  $sale
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $sale = Sale::find($id);
        $sale->delete();
        return $sale;
    }
}

resources/views/sales/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container" style="border:solid thin gray;">
   
    <div class="col-sm-12">
        <div class="card" style="color:green;">
 		<div class="card-header bg-primary">
	        <span class="text-white">Registro de Ventas</span>
	     </div>
 		</div>
	</div><br>
	<div class="col-sm-12">
		<p class="card-title text-right" style="margin-right: 50px;">Folio Venta: 
			@if(!empty($sale))
                 {{ $sale->id + 1 }}
              @else
                1
              @endif
	    </p>
	</div>

    <createsales></createsales>       
    
</div>
@endsection

resources/views/sales/created.blade.php
<!-- Modal -->
<form method="POST" v-on:submit.prevent="createKeep">
<div class="modal fade" id="create" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Nueva Tarea</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <label for="customer_id">Crear Tarea</label>
        <input type="text" name="customer_id" class="form-control" v-model="newKeep">
        <span v-for="error in errors" class="text-danger">@{{ $error }}</span>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Guardar</button>
      </div>
    </div>
  </div>
</div>
</form>

resources/views/sales/edit.blade.php
<!-- Modal -->
<form method="POST" v-on:submit.prevent="updateKeep(fillKeep.id)">
<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Editar Tarea</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <label for="customer_id">Actualizar Tarea</label>
        <input type="text" name="customer_id" class="form-control" v-model="fillKeep.customer_id">
        <span v-for="error in errors" class="text-danger">@{{ $error }}</span>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Actualizar</button>
      </div>
    </div>
  </div>
</div>
</form>

resources/views/sales/index.blade.php
@extends('layouts.app')
 
@section('content')
    
<div class="container">
    

    

   <div class="row">

       <div class="col-8">
           <h4 class="text-primary" style="position: absolute;
   bottom:0px; top:12px;">Ventas activas</h4>
       </div>
       <div class="col text-right">

           <a href="{{ route('sales.create') }}" class="btn btn-primary btn-lg" style="color:white">
            <i style="font-size:40px; color:#38c172; vertical-align:middle; " class="material-icons">add_circle</i> 
              Nueva Venta</a>
       </div>
       

   </div>
   <hr>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Folio Venta</th>
          <th scope="col">Clave Cliente</th>
          <th scope="col">Nombre</th>
          <th scope="col">Total</th>
          <th scope="col">Fecha</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($sales as $sale)
            <tr>
              <td>{{$sale->id}}</td>
              <td>{{$sale->customer_id}}</td>
              <td>{{ $sale->customer->full_name }}</td>
              <td>{{$sale->total_owed}}</td>
              <td>{{$sale->created_at}}</td>
            </tr>
           
        @endforeach
      </tbody>
    </table>
  
    {!! $sales->links() !!}
</div>
      
@endsection