routes/web.php
<?php
use Illuminate\Support\Facades\Input as Input;
use App\Customer;
use App\Article;
use App\Config;
use App\Sale;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('customers','CustomerController');
Route::resource('articles','ArticleController');
Route::resource('configs','ConfigController');
Route::resource('sales','SaleController');


Route::get('/getSales', 'SaleController@getSales');

Route::get('/customersget/',function(){
 $query = Input::get('query');
 $customers = Customer::where('name','like','%'.$query.'%')->orWhere('father_lastname','like','%'.$query.'%')->orWhere('mother_lastname','like','%'.$query.'%')->get();
 return response()->json($customers);
});

Route::get('/articlesget',function(){
 $queryart = Input::get('queryart');
 $articles = Article::where('description','like','%'.$queryart.'%')->orWhere('model','like','%'.$queryart.'%')->get();
 return response()->json($articles);
});

Route::get('/getprice',function(){
 $article_id = Input::get('id');
 $config = Config::orderBy('created_at','desc')->first();
 $article = Article::find($article_id);
 //Precio = Precio Articulo X (1 + (Tasa Financiamiento X Plazo Máximo) /100)
 $price = $article->price * (1+($config->financing_rate * $config->deadline) / 100);
 return response()->json(round($price,2));
 // $articles = Article::where('description','like','%'.$queryart.'%')->orWhere('model','like','%'.$queryart.'%')->get();
 // return response()->json($articles);
});

Route::get('/getTotales',function(){
 $sumAmount = Input::get('sumAmount');
 $config = Config::orderBy('created_at','DESC')->first();
 $totales["amount"] = round($sumAmount,2);
 $totales["hooking"] =  round(($config->hooking_percentage/100) * $totales["amount"],2);
 $totales["hooking_bonus"] = round($totales["hooking"] * (($config->financing_rate * $config->deadline) /100),2);
 $totales["total"] =   round($totales["amount"] - $totales["hooking"] - $totales["hooking_bonus"],2);
 return response()->json($totales);
});

Route::get('/getPlazos',function(){
 $sumAmount = Input::get('sumAmount');
 $config = Config::orderBy('created_at','DESC')->first();

 $plazos[3]["precio_contado"] = $sumAmount / (1 + (($config->financing_rate * $config->deadline) / 100));
 $plazos[3]["plazo"] = 3;
 $plazos[3]["total"] = round($plazos[3]["precio_contado"] * (1 + ($config->financing_rate * 3) / 100),2);
 $plazos[3]["abono"] = round($plazos[3]["total"] / 3,2);
 $plazos[3]["ahorro"] = round($sumAmount - $plazos[3]["total"],2);

 $plazos[6]["plazo"] = 6;
 $plazos[6]["total"] =  round($plazos[3]["precio_contado"] * (1 + ($config->financing_rate * 6) / 100),2);
 $plazos[6]["abono"] = round($plazos[6]["total"] / 6,2);
 $plazos[6]["ahorro"] = round($sumAmount - $plazos[6]["total"],2);

 $plazos[9]["plazo"] = 9;
 $plazos[9]["total"] = round($plazos[3]["precio_contado"] * (1 + ($config->financing_rate * 9) / 100),2);
 $plazos[9]["abono"] = round($plazos[9]["total"] / 9,2);
 $plazos[9]["ahorro"] = round($sumAmount - $plazos[9]["total"],2);

 $plazos[12]["plazo"] = 12;
 $plazos[12]["total"] = round($plazos[3]["precio_contado"] * (1 + ($config->financing_rate * 12) / 100),2);
 $plazos[12]["abono"] = round($plazos[12]["total"] / 12,2);
 $plazos[12]["ahorro"] = round($sumAmount - $plazos[12]["total"],2);

 return response()->json($plazos);
});

Route::post('/saveSale',function(){
	//QUITAR EXISTENCIAS DE LOS ARTÍCULOS
	$articles = Input::get('articles');
	foreach ($articles as $art) {

		$article = Article::find($art["id"]);
		$article->existence = $article->existence - $art["quantity"];
		$article->save();
	}

	$config = Config::orderBy('created_at','DESC')->first();
	$sale = new Sale;
	$sale->customer_id = Input::get('customer_id');
	$sale->hooking = Input::get('hooking');
	$sale->hooking_bonus = Input::get('hooking_bonus');
	$sale->total_owed = Input::get('total_owed');
	$sale->monthly_payment_number = Input::get('monthly_payment_number');
	$sale->cash_price = Input::get('total_owed') / (1 + (($config->financing_rate * $config->deadline) / 100));
	$sale->payment_ammount = round( Input::get('total_owed')/ $sale->monthly_payment_number ,2);
 	$sale->monthly_payment_number = Input::get('monthly_payment_number');
 	$sale->save();
 	return response()->json($sale);
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = [
        'description', 'price', 'existence','model'
    ];
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::latest()->paginate(5);
  
        return view('articles.index',compact('articles'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $articles = Article::all();
        $article = $articles->last();

        return view('articles.create',compact('article'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $messages = [
            'description.required' => 'Descripción es requerido.',
            'price.required' => 'Precio es requerido.',
            'price.numeric' => 'El precio debe ser un número',
            'existence.required' => 'Existencia es requerido.',
            'existence.numeric' => 'La existencia debe ser un número',
        ];

        $request->validate([
            'description' => 'required',
            'price' => 'required',
            'price' => 'numeric',
            'existence' => 'required',
            'existence' => 'numeric',
        ], $messages);
  
  
        Article::create($request->all());
   
        return redirect()->route('articles.index')
                        ->with('success','“Bien Hecho. El artículo ha sido registrado correctamente”.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        return view('articles.edit',compact('article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Article $article)
    {
        $messages = [
            'description.required' => 'Descripción es requerido.',
            'price.required' => 'Precio es requerido.',
            'price.numeric' => 'El precio debe ser un número',
            'existence.required' => 'Existencia es requerido.',
            'existence.numeric' => 'La existencia debe ser un número',
        ];

        $request->validate([
            'description' => 'required',
            'price' => 'required',
            'price' => 'numeric',
            'existence' => 'required',
            'existence' => 'numeric',
        ], $messages);
  
        $article->update($request->all());
  
        return redirect()->route('articles.index')
                        ->with('success','Se actualizó el Artículo con éxito.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        //
    }
}

resources/views/articles/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    
    <div class="card" style="color:green;">

      <div class="card-header bg-primary">
        <span class="text-white">Registro de Artículos</span>
      </div>

   
    
        <div class="card-body">
            <p class="card-title text-right" style="margin-right: 50px;">Clave:
              @if(!empty($article))
                 {{ $article->id + 1 }}
              @else
                1
              @endif
            
            </p>


            <form  action="{{ route('articles.store') }}" method="POST">
                @csrf <!-- {{ csrf_field() }} -->
                
              <div class="form-group row text-right">
                <label for="description" class="col-sm-2 col-form-label">Descripción:</label>
                <div class="col-sm-4">
                  <input type="text" name="description" class="form-control" id="description" value="{{ old('description') }}">
                </div>
              </div>

              <div class="form-group row text-right">
                <label for="model" class="col-sm-2 col-form-label">Modelo:</label>
                <div class="col-sm-4">
                  <input type="text" name="model" class="form-control" id="model" value="{{ old('model') }}">
                </div>
              </div>

              <div class="form-group row text-right">
                <label for="price" class="col-sm-2 col-form-label">Precio:</label>
                <div class="col-sm-4">
                  <input type="text" name="price" class="form-control" id="price" value="{{ old('price') }}">
                </div>
              </div>

              <div class="form-group row text-right">
                <label for="existence" class="col-sm-2 col-form-label">Existencia:</label>
                <div class="col-sm-4">
                  <input type="text" name="existence" class="form-control" id="existence" value="{{ old('existence') }}">
                </div>
              </div>

              <div class="form-group row text-right">
                <div class="col-sm-10">
                  <a class="btn btn-success" href="{{ route('articles.index') }}">Cancelar</a>
                  <button type="submit" class="btn btn-success">Guardar</button>
                </div>
              </div>

            </form>
    
        </div>

    </div>  
</div>

@endsection

resources/views/articles/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    
    <div class="card" style="color:green;">

      <div class="card-header bg-primary">
        <span class="text-white">Editar Artículo</span>
      </div>
    
        <div class="card-body">
            <p class="card-title text-right" style="margin-right: 50px;">Clave: {{$article->id}} </p>


            <form  action="{{ route('articles.update',$article->id) }}" method="POST">
                @csrf <!-- {{ csrf_field() }} -->
                @method('PUT')
              <div class="form-group row text-right">
                <label for="description" class="col-sm-2 col-form-label">Descripción:</label>
                <div class="col-sm-4">
                  <input type="text" name="description" class="form-control" id="description" value="{{ $article->description }}">
                </div>
              </div>

              <div class="form-group row text-right">
                <label for="model" class="col-sm-2 col-form-label">Modelo:</label>
                <div class="col-sm-4">
                  <input type="text" name="model" class="form-control" id="model" value="{{ $article->model }}">
                </div>
              </div>

              <div class="form-group row text-right">
                <label for="mother_lastname" class="col-sm-2 col-form-label">Precio:</label>
                <div class="col-sm-4">
                  <input type="text" name="price" class="form-control" id="price" value="{{ $article->price }}">
                </div>
              </div>

              <div class="form-group row text-right">
                <label for="existence" class="col-sm-2 col-form-label">Existencia:</label>
                <div class="col-sm-4">
                  <input type="text" name="existence" class="form-control" id="existence" value="{{ $article->existence }}">
                </div>
              </div>

              <div class="form-group row text-right">
                <div class="col-sm-10">
                  <a class="btn btn-success" href="{{ route('articles.index') }}">Cancelar</a>
                  <button type="submit" class="btn btn-success">Guardar</button>
                </div>
              </div>

            </form>
    
        </div>

    </div>
</div>

@endsection

resources/views/articles/index.blade.php
@extends('layouts.app')
 
@section('content')
    
<div class="container">
    


   <div class="row">

       <div class="col-8">
           <h4 class="text-primary" style="position: absolute;
   bottom:0px; top:12px;">Artículos Registrados</h4>
       </div>
       <div class="col text-right">

           <a href="{{ route('articles.create') }}" class="btn btn-primary btn-lg" style="color:white">
            <i style="font-size:40px; color:#38c172; vertical-align:middle; " class="material-icons">add_circle</i> 
              Nuevo Artículo</a>
       </div>
       

   </div>
   <hr>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Clave Artículo</th>
          <th scope="col">Descripción</th>
          <th width="280px">Acción</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($articles as $article)
            <tr>
              <td>{{$article->id}}</td>
              <td>{{$article->description}}</td>
              <td>
     
                <a title="editar cliente" href="{{ route('articles.edit',$article->id) }}"><i class="material-icons">edit</i>
                </a>

              </td>
            </tr>
           
        @endforeach
      </tbody>
    </table>
  
    {!! $articles->links() !!}
</div>
      
@endsection